 development:
    adapter: postgresql
    encoding: unicode
    database: twittergame_development
    pool: 5
    host: localhost
    username:
    password:


  test:
    adapter: postgresql
    encoding: unicode
    database: twittergame_test
    pool: 5
    host: localhost
    username:
    password:
